### ISSUE TITLE
set1.txt output should have CPU: C at t=26ms

### ISSUE THREAD

**Issue by ramoncomendadorjr** [omeeeeeeee/cs140project1#4]
## Current Output
At Time = 25
A, B DONE
Queues: [D]; [C]; []
CPU: D
C DEMOTED

At Time = 26
A, B DONE
Queues: []; [C, D]; []
CPU: D
C, D DEMOTED

At Time = 27
A, B DONE
Queues: []; [C, D]; []
CPU: C
C, D DEMOTED

## Written Solution
<img width="1231" alt="Screenshot 2024-12-20 at 3 07 09 PM" src="https://github.com/user-attachments/assets/2fd68fc1-46c2-4f2d-951d-63c636b6b7b9" />

**Comment by omeeeeeeee** [comment]
resolved in mon branch
